### ISSUE TITLE
set "redirect.disable" guzzle parameter

### ISSUE THREAD

**Issue by zroger** [minkphp/MinkGoutteDriver#14]
in fabpot/Goutte#85,  they changed the way they create the guzzle client, passing the `redirect.disable = true` parameter since redirects are handled by BrowserKit, not guzzle.

```
$this->client = new GuzzleClient('', array('redirect.disable' => true));
```

Since the goutte driver creates a guzzle service in the dependency injection container, these defaults should be matched by the driver.  I was able to get this working by adding the param in my behat.yml file, but ran into trouble adding it to the goutte.xml (part of Behat/MinkExtension) because the Symfony tree builder complained about having a variable with a period in the name.

Here's what I did in my behat.yml:

```
default:
  extensions:
    Behat\MinkExtension\Extension:
      goutte: 
        guzzle_parameters:
          redirect.disable: true
```

BTW, the issue I had that led to me finding this was that an HTTP response with set-cookie headers as well as a location header would process the redirect without handling the new cookies.  This is because the redirect was being handled by guzzle, instead of BrowserKit as Goutte expects.
