### ISSUE TITLE
verify: false in Guzzle parameters no longer works with Goutte 3

### ISSUE THREAD

**Issue by clemf** [minkphp/MinkGoutteDriver#68]
With the addition of Goutte 3 support in version 1.2.0, my scenarios are now throwing SSL errors even though I have the recommended settings from the [Mink Extension documentation](https://github.com/Behat/MinkExtension/blob/master/doc/index.rst#drivers):

```
default:
    extensions:
        Behat\MinkExtension:
            sessions:
                my_session:
                    goutte:
                        guzzle_parameters:
                            verify: false
```

If I downgrade to version 1.1.0 (and therefore to Goutte 2 & Guzzle 5), my scenarios work again and the SSL cert is ignored as expected. I'm not exactly sure if the problem is in the driver, or something in Goutte or Guzzle but my problem was definitely triggered by the driver's update to 1.2.0.
