### ISSUE TITLE
Checkbox "foo" is not checked, but it should be.

### ISSUE THREAD

**Issue by gimler** [minkphp/MinkGoutteDriver#74]
The following doesn't work with goutte but with selenium driver
```gherkin
Feature: checkbox

  Scenario: create a new customer
    Given I am on "http://127.0.0.1:8080/form.html"

    And the "foo" checkbox should be checked
```

see also #56 

composer.json
```json
{
    "require": {
        "behat/behat": "3.1.*",
        "behat/mink": "1.7.1",
        "behat/mink-extension": "2.2",
        "behat/mink-goutte-driver": "1.2.1"
    },
    "config": {
        "bin-dir": "bin/"
    }
}
```

html
```html
<html>
<head>
</head>
<body>
<form action="#">

    <input id="foo" name="foo" type="checkbox" checked="checked" value="1">
    <input type="submit" value="send">

</form>
</body>
</html>
```

behat.yml
```
default:
    extensions:
        Behat\MinkExtension: 
            base_url: 'http://127.0.0.1'
            show_cmd: 'firefox %s'
            default_session: http
            javascript_session: javascript
            sessions:
                http:
                    goutte:
                        guzzle_parameters:
                            verify: false
                javascript:
                    selenium2:
                        wd_host: "http://localhost:8643/wd/hub"
        Sanpi\Behatch\Extension: ~

    suites:
        default:
            contexts:
                - FeatureContext
                - Behat\MinkExtension\Context\MinkContext
                - behatch:browser

```

run with `php -S 127.0.0.1:8080`
